---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04
      provider: parallels
  - name: ubuntu-12.04
    driver:
      box: express42/ubuntu12.04-chef11
      provider: parallels

suites:
  - name: express42
    run_list:
      - recipe[express42::default]
      - recipe[express42::mail]
      - recipe[express42::network]
      - recipe[express42::packages]
    attributes:
